server:
  port: 8080

spring:
  ai:
   openai:
     api-key: ${OPEN_ai_KEY}
     model: gpt-4o-mini
   autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration


springdoc:
  swagger-ui:
    path: /swagger
